### ISSUE TITLE
level param for streams

### ISSUE THREAD

**Issue by crotwell** [EarthScope/ringserver#38]
This URL works correctly:
```
curl 'http://rtserve.iris.washington.edu/streams?match=CO_BIRD_00_HHZ'        
CO_BIRD_00_HHZ/MSEED  2022-09-12T18:48:22.389999Z  2022-09-12T19:41:41.839999Z
```
but if a level parameter is added, it returns something that looks like what should be returned from `streamids` instead of `streams`:
```
curl 'http://rtserve.iris.washington.edu/streams?match=CO_BIRD_00_HHZ&level=4'
CO_BIRD_00_HHZ
```
From the docs it would seem that `level=4` is not valid for the `streams` endpoint. If that is true, I think ringserver should error rather than output something from a different endpoint. Otherwise it is confusing as adding `level=4` seems like it should limit the output to streams that "are" level 4, but that is not what happens.

**Comment by chad-earthscope** [comment]
It is common practice for HTTP services to ignore parameters they do not understand (not my personal favorite as a user of them but is is easy on implementors).

This issue is now moot as the `level` parameter functionality has been removed.  The feature was not general for arbitrary stream IDs.  With the new JSON output clients can consume the stream list and summarize the streams however they wish, which is much more powerful.
